@startuml SD_MATCH_DEL
hide footbox
autonumber
skinparam shadowing false
actor User as u
participant ":View" as v <<view>>
participant ":Ctrl" as c <<ctrl>>
participant ":SelectedTournoi" as f <<entity>> 

activate u
u -> v : btDelMatch.setOnAction()
activate v
v->c: delSelectedMatch(mSel.getPl1Name(),mSel.getPl2Name(),mSel.getR())
activate c
c ->f:deleteMatch(m)
deactivate c
v -> v : displayMatch(selectedTrnm().getMatchs()) 
@enduml